Repository meanii/sync.ssh, pull requests merged in 2022-08, with the labels that each got.

#4 improved doc!
  README.md
Labels: documentation

#17 improved installer.sh!
  installer.sh
Labels: bug

#22 Update README.md
  README.md
Labels: documentation

#23 issue #7, add dymanic branch! right now its just pushing on main
  cmd/init.go
  github/service.go
  model/user.go
Labels: enhancement

#25 Revert "fixed typos"
  assets/README.md
Labels: documentation

#31 fix a "Failed at step EXEC spawning... Permission denied" bug.
  installer.sh
Labels: bug

#36 added GitPath in list
  cmd/list.go
  go.mod
  go.sum
Labels: enhancement, good first issue
